name: 'ci'
on: # rebuild any PRs and main branch changes
  push:

jobs:
  tests: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          npm run all

  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the dist/ directory
        run: |
          npm run build
          npm run package

      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff

      # If index.js was different than expected, upload the expected version as an artifact
      - uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/

  integrate:
    runs-on: ubuntu-latest
    needs: [tests, check-dist]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run integration action
        id: integrate
        uses: ./
        with:
          branch-pattern: "^for_(?<base>[-a-zA-Z/._0-9]+)_(?<identifier>[a-zA-Z]+)$"
          create-base-if-missing: true
          delete-source: true
          abort-integration-if-different-commits-on-origin: true
      - name: Outputs
        env:
          INTEGRATION_TARGET: ${{ steps.integrate.outputs.integration-target }}
          DID_INTEGRATE: ${{ steps.integrate.outputs.did-integrate }}
          ABORTION_REASON: ${{ steps.integrate.outputs.abortion-reason }}
          DELETED_SOURCE: ${{ steps.integrate.outputs.deleted-source }}
          CREATED_BASE: ${{ steps.integrate.outputs.created-base }}
        shell: bash
        run: |
            echo "Outputs:"
            echo "integration-target: ${INTEGRATION_TARGET}"
            echo "did-integrate: ${DID_INTEGRATE}"
            echo "abortion-reason: ${ABORTION_REASON}"
            echo "deleted-source: ${DELETED_SOURCE}"
            echo "created-base: ${CREATED_BASE}"
